<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminOperation.aspx.cs" Inherits="AdminOperation" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        #form1
        {
            height: 533px;
            margin-bottom: 0px;
        }
        .style1
        {
            width: 88%;
            height: 815px;
        }
        .style2
        {
        }
        .style3
        {
            height: 100px;
        }
        .style5
        {
            height: 120px;
            width: 757px;
        }
    </style>
</head>
<body style="height: 795px; width: 868px;">
    <form id="form1" runat="server">
    <table class="style1" style="background-image: url('Images/Bank10.jpg')">
        <tr>
            <td class="style3">
            <h2><b><i><u>ADMIN OPERATIONS</u></i></b></h2></td></td>
        </tr>
        <tr>
            <td class="style2">
                <table class="style5">
                    <tr>
                        <td>
                            <asp:GridView ID="GridView1" runat="server" 
                                BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" 
                                CellPadding="4" DataSourceID="SqlDataSource1" AllowSorting="True" 
                                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" >
                                <Columns>
                                    <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                                    <asp:BoundField DataField="gender" HeaderText="gender" 
                                        SortExpression="gender" />
                                    <asp:BoundField DataField="dob" HeaderText="dob" SortExpression="dob" />
                                    <asp:BoundField DataField="uname" HeaderText="uname" SortExpression="uname" />
                                    <asp:BoundField DataField="password" HeaderText="password" 
                                        SortExpression="password" />
                                    <asp:BoundField DataField="cpassword" HeaderText="cpassword" 
                                        SortExpression="cpassword" />
                                    <asp:BoundField DataField="emailid" HeaderText="emailid" 
                                        SortExpression="emailid" />
                                    <asp:BoundField DataField="occupation" HeaderText="occupation" 
                                        SortExpression="occupation" />
                                    <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                                    <asp:BoundField DataField="mobileno" HeaderText="mobileno" 
                                        SortExpression="mobileno" />
                                    <asp:BoundField DataField="amt" HeaderText="amt" SortExpression="amt" />
                                </Columns>
                                <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
                                <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
                                <RowStyle BackColor="White" ForeColor="#330099" />
                                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                                <SortedAscendingCellStyle BackColor="#FEFCEB" />
                                <SortedAscendingHeaderStyle BackColor="#AF0101" />
                                <SortedDescendingCellStyle BackColor="#F6F0C0" />
                                <SortedDescendingHeaderStyle BackColor="#7E0000" />
                            </asp:GridView>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                                ConnectionString="<%$ ConnectionStrings:mycon %>" 
                                SelectCommand="SELECT * FROM [register]" UpdateCommand ="update [register] set [name]=@name,[gender]=@gender  ,[password]=@password,[cpassword]=@cpassword,[uname]=@uname,[occupation]=@occupation,[city]=@city,[mobileno]=@mobileno  where [emailid]=@emailid  "></asp:SqlDataSource>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    </form>
</body>
</html>
